server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由

        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**   #断言,路径相匹配的进行路由
            #- After=2021-04-16T10:03:34.102+08:00[Asia/Shanghai]
            #- Before=2021-04-16T10:03:34.102+08:00[Asia/Shanghai]
            #- Between=2021-04-16T10:03:34.102+08:00[Asia/Shanghai] ,  2021-04-16T11:03:34.102+08:00[Asia/Shanghai]
            #- Cookie=username,hq    #并且Cookie是username=zhangshuai才能访问
            #- Header=X-Request-Id, \d+   #请求头中要有X-Request-Id属性并且值为整数的正则表达式
            #- Host=**.atguigu.com
            #- Method=post
            #- Query=username, \d+ #要有参数名称并且是正整数才能路由





eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka


